package src.My.rules
//declare any global variables here
import My.Project.Thesis.Ontology.ControllerFact;
import My.Project.Thesis.Ontology.DeviceState;
import My.Project.Thesis.Ontology.DeviceInstruct;
import My.Project.Thesis.Ontology.CommandTypes;
import function My.prototype.DroolsUtility.help;


rule "Instr changeMax HD"
    when
      $f:ControllerFact(isGoodCondition==true)
                and
         $s:DeviceState($f.maxLoad>0)

    then
        $f.needsChangeLoad=true;
		$f.isGoodCondition=false;
		help(drools,$f.ID,$s);
end